set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:RGB"

bind r source-file ~/.config/tmux/tmux.conf
set-option -sa terminal-overrides ",xterm*:Tc"

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind P paste-buffer

set -g status-style 'fg=#DCD7BA,bg=#16161D'
set -g window-status-current-style 'fg=#16161D,bg=#DCD7BA'  

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'omerxx/tmux-floax'

set -g @continuum-restore 'on'
set -g @floax-bind 'j'

run '~/.tmux/plugins/tpm/tpm'
